apiVersion: v2
name: payflow
description: Payment Processing Demo for InfraSage RCA
type: application
version: 0.0.2
appVersion: "v1.1.0-hotfix"
maintainers:
  - name: InfraSage
    email: demo@infrasage.io
keywords:
  - payment
  - demo
  - rca
