apiVersion: v2
name: payflow
description: Payment Processing Demo for InfraSage RCA
type: application
version: 0.0.5
appVersion: "0.0.5"
maintainers:
  - name: InfraSage
    email: demo@infrasage.io
keywords:
  - payment
  - demo
  - rca
