apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payflow.fullname" . }}-secret
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
