{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "payflow.serviceAccountName" . }}
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
{{- end }}
